#!/usr/bin/env python3
"""Generate Quarto object reference pages from the DASDAE inventory spec."""

from __future__ import annotations

from pathlib import Path
import re

import yaml


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "specs" / "dasdae-inventory.yml"
OUT_DIR = ROOT / "References"

GENERATED_NOTICE = "<!-- Generated by scripts/generate_references.py; edit specs/dasdae-inventory.yml instead. -->"


def load_spec() -> dict:
    with SPEC_PATH.open() as file:
        return yaml.safe_load(file)


def class_name(node_id: str, node: dict) -> str:
    return str(node.get("label") or node_id)


def page_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]", "", name) + ".qmd"


def class_maps(spec: dict) -> tuple[dict[str, str], dict[str, str], dict[str, str]]:
    id_to_name: dict[str, str] = {}
    id_to_page: dict[str, str] = {}
    token_to_name: dict[str, str] = {}

    for node_id, node in sorted(spec["nodes"].items()):
        name = class_name(node_id, node)
        id_to_name[node_id] = name
        id_to_page[node_id] = page_name(name)
        token_to_name[name] = name
        token_to_name[node_id] = name
        display = node.get("display")
        if display:
            token_to_name[str(display)] = name

    return id_to_name, id_to_page, token_to_name


def link(name: str, text: str | None = None) -> str:
    return f"[{text or name}]({page_name(name)})"


def link_type(value: object, token_to_name: dict[str, str]) -> str:
    text = str(value or "")

    def replace(match: re.Match[str]) -> str:
        token = match.group(0)
        target = token_to_name.get(token)
        if target is None:
            return token
        return link(target, token)

    return re.sub(r"\b[A-Za-z_][A-Za-z0-9_]*\b", replace, text).replace("|", r"\|")


def edge_parts(edge: object) -> tuple[str, str, str]:
    if isinstance(edge, dict):
        return str(edge.get("from", "")), str(edge.get("to", "")), str(edge.get("label", ""))
    if isinstance(edge, list):
        items = [str(item) for item in edge]
        while len(items) < 3:
            items.append("")
        return items[0], items[1], items[2]
    raise TypeError(f"Unsupported edge shape: {edge!r}")


def relation_list(
    edges: list,
    node_id: str,
    id_to_name: dict[str, str],
    *,
    direction: str,
    default_label: str = "",
) -> list[str]:
    rows: list[str] = []
    for edge in edges or []:
        source, target, label = edge_parts(edge)
        if direction == "out" and source == node_id:
            target_name = id_to_name.get(target, target)
            relation = label or default_label
            if relation:
                rows.append(f"- {relation} {link(target_name)}")
            else:
                rows.append(f"- {link(target_name)}")
        elif direction == "in" and target == node_id:
            source_name = id_to_name.get(source, source)
            relation = label or default_label
            if relation:
                rows.append(f"- {relation} from {link(source_name)}")
            else:
                rows.append(f"- {link(source_name)}")
    return rows


def attributes_table(node: dict, token_to_name: dict[str, str]) -> str:
    attrs = node.get("attributes") or []
    if not attrs:
        return "_No attributes listed._\n"

    rows = ["| Name | Type | Description |", "|---|---|---|"]
    for attr in attrs:
        name = str(attr.get("name", ""))
        attr_type = link_type(attr.get("type", ""), token_to_name)
        description = str(attr.get("description", "")).replace("|", r"\|")
        rows.append(f"| `{name}` | {attr_type} | {description} |")
    return "\n".join(rows) + "\n"


def section(title: str, rows: list[str]) -> str:
    if not rows:
        return f"## {title}\n\n_None._\n"
    return f"## {title}\n\n" + "\n".join(rows) + "\n"


def object_page(
    spec: dict,
    node_id: str,
    node: dict,
    id_to_name: dict[str, str],
    token_to_name: dict[str, str],
) -> str:
    name = class_name(node_id, node)
    summary = str(node.get("summary", ""))
    display = str(node.get("display", ""))
    aliases = []
    for value in (node_id, display):
        if value and value != name and value not in aliases:
            aliases.append(value)
    alias_text = ", ".join(f"`{alias}`" for alias in aliases)

    containment_children = relation_list(spec.get("edges"), node_id, id_to_name, direction="out")
    containment_parents = relation_list(spec.get("edges"), node_id, id_to_name, direction="in")
    references_out = relation_list(
        spec.get("references"),
        node_id,
        id_to_name,
        direction="out",
        default_label=str(spec.get("reference_label") or "references"),
    )
    references_in = relation_list(
        spec.get("references"),
        node_id,
        id_to_name,
        direction="in",
        default_label=str(spec.get("reference_label") or "referenced"),
    )

    parts = [
        "---",
        f'title: "{name}"',
        "sidebar: references",
        "---",
        "",
        GENERATED_NOTICE,
        "",
        summary,
        "",
    ]
    note = str(node.get("note", ""))
    if note:
        parts.extend(["::: {.note}", note, ":::", ""])
    if alias_text:
        parts.extend(["Aliases: " + alias_text, ""])
    parts.extend(
        [
            "## Attributes",
            "",
            attributes_table(node, token_to_name),
            section("Contains", containment_children),
            section("Contained By", containment_parents),
            section("References", references_out),
            section("Referenced By", references_in),
        ]
    )
    return "\n".join(parts).rstrip() + "\n"


def index_page(spec: dict, id_to_name: dict[str, str]) -> str:
    rows = ["| Object | Summary |", "|---|---|"]
    for node_id, node in sorted(spec["nodes"].items(), key=lambda item: class_name(item[0], item[1])):
        name = id_to_name[node_id]
        summary = str(node.get("summary", "")).replace("|", r"\|")
        rows.append(f"| {link(name)} | {summary} |")
    return "\n".join(
        [
            "---",
            'title: "Object Reference"',
            "sidebar: references",
            "---",
            "",
            GENERATED_NOTICE,
            "",
            "These pages are generated from `specs/dasdae-inventory.yml`.",
            "",
            *rows,
            "",
        ]
    )


def main() -> None:
    spec = load_spec()
    OUT_DIR.mkdir(exist_ok=True)
    id_to_name, _, token_to_name = class_maps(spec)

    (OUT_DIR / "index.qmd").write_text(index_page(spec, id_to_name))
    for node_id, node in sorted(spec["nodes"].items()):
        name = id_to_name[node_id]
        (OUT_DIR / page_name(name)).write_text(object_page(spec, node_id, node, id_to_name, token_to_name))


if __name__ == "__main__":
    main()
